# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SolutionArchitecture' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'app_di', :path => '../app-di'
  pod 'lib_basic_swift', :path => '../lib-basic/src/iOSMain/swift'
  pod 'app_di_swift', :path => '../app-di/src/iOSMain/swift'
  pod 'solution_ab_api_swift', :path => '../solution-ab-api/src/iOSMain/swift'
  pod 'solution_ab_impl_swift', :path => '../solution-ab-impl/src/iOSMain/swift'
  pod 'solution_attention_api_swift', :path => '../solution-attention-api/src/iOSMain/swift'
  pod 'solution_attention_impl_swift', :path => '../solution-attention-impl/src/iOSMain/swift'
  pod 'solution_auth_api_swift', :path => '../solution-auth-api/src/iOSMain/swift'
  pod 'solution_auth_impl_swift', :path => '../solution-auth-impl/src/iOSMain/swift'
  pod 'solution_order_api_swift', :path => '../solution-order-api/src/iOSMain/swift'
  pod 'solution_order_impl_swift', :path => '../solution-order-impl/src/iOSMain/swift'
  pod 'solution_search_form_api_swift', :path => '../solution-search-form-api/src/iOSMain/swift'
  pod 'solution_search_form_impl_swift', :path => '../solution-search-form-impl/src/iOSMain/swift'
  pod 'solution_search_result_api_swift', :path => '../solution-search-result-api/src/iOSMain/swift'
  pod 'solution_search_result_impl_swift', :path => '../solution-search-result-impl/src/iOSMain/swift'
  pod 'solution_search_start_api_swift', :path => '../solution-search-start-api/src/iOSMain/swift'
  pod 'solution_search_start_impl_swift', :path => '../solution-search-start-impl/src/iOSMain/swift'
  pod 'solution_settings_api_swift', :path => '../solution-settings-api/src/iOSMain/swift'
  pod 'solution_settings_impl_swift', :path => '../solution-settings-impl/src/iOSMain/swift'
  pod 'solution_tab_search_api_swift', :path => '../solution-tab-search-api/src/iOSMain/swift'
  pod 'solution_tab_search_impl_swift', :path => '../solution-tab-search-impl/src/iOSMain/swift'
  pod 'solution_tabs_api_swift', :path => '../solution-tabs-api/src/iOSMain/swift'
  pod 'solution_tabs_impl_swift', :path => '../solution-tabs-impl/src/iOSMain/swift'
  pod 'solution_bonus_api_swift', :path => '../solution-bonus-api/src/iOSMain/swift'
  pod 'solution_bonus_impl_swift', :path => '../solution-bonus-impl/solution/src/iOSMain/swift'
  pod 'solution_buy_api_swift', :path => '../solution-buy-api/src/iOSMain/swift'
  pod 'solution_buy_impl_swift', :path => '../solution-buy-impl/src/iOSMain/swift'
  pod 'solution_weather_api_swift', :path => '../solution-weather-api/src/iOSMain/swift'
  pod 'solution_weather_impl_swift', :path => '../solution-weather-impl/src/iOSMain/swift'

  # Pods for SolutionArchitecture

  target 'SolutionArchitectureTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SolutionArchitectureUITests' do
    # Pods for testing
  end

end
