# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SolutionArchitecture' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'solution_ios', :path => '../../solution_ios'

  # Pods for SolutionArchitecture

  target 'SolutionArchitectureTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SolutionArchitectureUITests' do
    # Pods for testing
  end

end
